#!/bin/bash

export LIZARD_HOME="$HOME/Lizard"

# Setup.
SCRIPT="${BASH_SOURCE[0]}";
SCRIPT_DIR="$(dirname "$SCRIPT")"
while [[ -L "${SCRIPT_DIR}" ]] 
do
    SCRIPT_DIR="$(readlink "${SCRIPT_DIR}")"
done
SCRIPT="$(basename "$SCRIPT")"

if [[ $DEBUG == 1 ]]
then
    echo "SCRIPT = $SCRIPT"
    echo "SCRIPT_DIR = $SCRIPT_DIR"
fi

# Lizard
if [[ -z "$LIZARD_HOME" ]]
then 
    # Assume command in ${LIZARD_HOME}/lizard-cmds/bin
    LIZARD_HOME="${SCRIPT_DIR%/bin}"
    LIZARD_HOME="${SCRIPT_DIR%/lizard-*}"    
fi

LZ_CMDS="$LIZARD_HOME/lizard-cmds"
CMD="$SCRIPT_DIR/$SCRIPT"

## OTT (classpath processing)
source "$LZ_CMDS/bin/init"

## ---------------------------------
## if [[ -z $1 ]]
## then
##     echo "No location given" 2>&1 
##     exit 2
## fi

LOC_SRC=DB
LOC_DEST=DB1

rm -rf "$LOC_DEST"
mkdir -p "$LOC_DEST"

# Split into 

# SPO,POS,OSP


# tdb.CmdRewriterIndex
# SPO, POS, (POS->PSO), PSO

for X in SPO POS
do 
    echo "Copy $X : $LOC_SRC -> $LOC_DEST"
    cp "$LOC_SRC/$X".* "$LOC_DEST"
done

CMD_IDX="com.hp.hpl.jena.tdb.store.bulkloader2.CmdIndexCopy"
echo "Rewrite POS to PSO : $LOC_SRC -> $LOC_DEST"
java -cp "$CP" $CMD_IDX "$LOC_SRC" POS "$LOC_DEST" PSO

## for X in SPO POS OSP
## do
##     lz shard --loc $LOCATION SPO 2
## done
## 
## # Nodes

echo "Copy node table"
cp "$LOC_SRC/node"* "$LOC_DEST"

echo "Copy TDB configuration"
echo "{ \"tdb.triple_indexes\" : [ \"SPO\" , \"POS\" , \"PSO\" ] }" > "$LOC_DEST"/tdb.cfg
