#!/bin/bash
# Run Fuseki 

LIZARD_HOME="${LIZARD_HOME:-$HOME/Lizard}"
LZ_CMDS="$LIZARD_HOME/lizard-cmds"
source "$LZ_CMDS/bin/init"

VER_FU=2.0.1-SNAPSHOT

CP="$CP:${M2_REPO}/org/apache/jena/jena-fuseki-server/${VER_FU}/jena-fuseki-server-${VER_FU}.jar"
# Remove slf4j (inside fuseki server)
CP="$(echo $CP | perl -p -e 's!:[^:]*/org/slf4j/[^:]*!:!g')"

FUSEKI_LOG=${FUSEKI_LOG:-}
JVM_ARGS="${JVM_ARGS:--Xmx1200M}"

export FUSEKI_HOME=$HOME/Jena/jena-fuseki2/jena-fuseki-core
export FUSEKI_BASE=$PWD/run
[[ -e $FUSEKI_BASE ]] || mkdir -p $FUSEKI_BASE

X=$(echo $CP | sed -e "s/:/\n"/g)

exec java -cp "$CP" $JVM_ARGS $FUSEKI_LOG org.apache.jena.fuseki.cmd.FusekiCmd "$@"
