#!/bin/bash

# May need to add in development specific setup here.

# For now:
# Temp fix until egit/jgit gets symbolic link handling
LIZARD_HOME=${LIZARD_HOME:-${HOME}/Lizard}

${LIZARD_HOME}/lizard-cmds/bin/lz "$@"
