#!/bin/bash

if (( $# == 0 ))
then
    echo "No input files" 1>&2
    echo "Usage: $(basename $0) FILE ..." 1>&2
    exit 1
fi

# Directory for Jena RDF term encoding for "BinaryRDF.thrift"
INC=$HOME/Jena/jena-arq/Grammar/

PKG="src/main/java/lizard/api/TLZ"
rm -f $PKG/*.java

THRIFT=$HOME/ASF/thrift-0.10.0/compiler/cpp/thrift

# No -r : do not generate code for included files.
$THRIFT -I $INC -out src/main/java -gen java "$@"

for f in $PKG/*.java
do
    perl -i.bak -p -e 's/^\@SuppressWarnings.*$/\@SuppressWarnings("all")/' $f
    rm $f.bak
done
