/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package lizard.api.TLZ;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

@SuppressWarnings("all")
public enum TLZ_PatchAction implements org.apache.thrift.TEnum {
  ADD(0),
  DEL(1);

  private final int value;

  private TLZ_PatchAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TLZ_PatchAction findByValue(int value) { 
    switch (value) {
      case 0:
        return ADD;
      case 1:
        return DEL;
      default:
        return null;
    }
  }
}
